### ISSUE TITLE
Pull down for filter

### ISSUE THREAD

**Issue by karmstro77** [Esri/InteractiveFilter#5]
I am unable to get a pull down list of filter values. I have set up a filter in the web map to use a list of unique values. When I use that web map in this template, the pull down list is gone. I have to manually enter the values. Is this a bug or does it not support pull down lists?

![image](https://cloud.githubusercontent.com/assets/6819070/10895256/3c10bda2-8181-11e5-9830-4c003385eb5e.png)

**Comment by kellyhutchins** [comment]
At this release it doesn't support dropdown lists for the values but we can look at adding this for a future release.

**Comment by karmstro77** [comment]
Any update on adding support for a configurable dropdown list? Thanks

**Comment by marissaAnn** [comment]
I'm also wondering if there is an update for this... I am currently working on trying to enhance the template with this exact functionality.

**Comment by kellyhutchins** [comment]
We added support for this at the last release. You can enable it by checking on the 'Display unique values in dropdown list' checkbox in the Filter section of the app's configuration panel. 
There is one small issue in that if your dataset has null values those will show up in the dropdown as a blank space. We are fixing that for the next release.

**Comment by marissaAnn** [comment]
Hi Kelly - 
I've recently experienced some issues with creating the drop down from unique values and am wondering if there is a template issue or if it's something on my end. I've switched back to the pre-auto complete version and am seeing errors when trying to filter on feature layers published as a map service. 

This public service is similar and showing the same errors: https://tigerweb.geo.census.gov/arcgis/rest/services/Census2010/CBSA/MapServer 

![filter-old-error](https://cloud.githubusercontent.com/assets/22507315/21820685/4f2e2a08-d736-11e6-9bcf-c5db7194fe82.png)

I'm curious if there is a configuration while publishing that I may be missing or if this is not a supported type? Services published as features are working fine. Thanks!

**Comment by kellyhutchins** [comment]
In your web map are you referencing an individual feature layer? For example: 

https://tigerweb.geo.census.gov/arcgis/rest/services/Census2010/CBSA/MapServer/0

The supportsDistinct operation is on the individual layer rather than the map service.

**Comment by marissaAnn** [comment]
Yup, I've actually tried using: 
https://tigerweb.geo.census.gov/arcgis/rest/services/Census2010/CBSA/MapServer/0 

With a filter on the name field

**Comment by kellyhutchins** [comment]
Is your app or web map public? If so can you share the link?

**Comment by marissaAnn** [comment]
Unfortunately I cannot share the app/map that's giving me issues within our portal. 

But when trying to recreate the issue using the above layer in our ArcGIS online account, everything seems to be working as it should.

**Comment by kellyhutchins** [comment]
@marissaAnn  looks like I missed updating this repo at the last release. I just updated it so can you download the code again and see if that resolves the issue you are experiencing?

**Comment by marissaAnn** [comment]
@kellyhutchins that did help - it is now working for map image layers - but only when adding them individually.

The below screenshot shows the same layer, but the first is nested within the service, and the second was added individually. 

![bcrterr4](https://cloud.githubusercontent.com/assets/22507315/21827279/98c3d7ca-d750-11e6-9364-dd2817cee9bb.png)

**Comment by kellyhutchins** [comment]
Its only supported by adding the individual layers. Can look at adding support for the map service for a future release.

**Comment by marissaAnn** [comment]
Ahh I see, thanks for the quick help with this!
