### ISSUE TITLE
Filter Not Loading for Coded Values w/ Field Name and Alias Difference

### ISSUE THREAD

**Issue by marissaAnn** [Esri/InteractiveFilter#9]
Hey @kellyhutchins 
Sorry to bug you again - but I'm hitting issues with this template.

I've noticed that the map is not loading the selected filter when trying to filter on fields with coded values, but only when the field name does not match the alias.

When trying to replicate the issue using the ArcGIS online template, I am not experiencing the problem. Wondering if there was another update that did not make it into this repository?

I'm using the most recent version, updated 7 days ago.

**Comment by kellyhutchins** [comment]
No all updates are included in this repository. Do you have a public url or steps I can use to try and reproduce the problem?

**Comment by marissaAnn** [comment]
Here's a public layer with a similar data structure to the private layer I'm using that's giving problems:

http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/SanFrancisco/311Incidents/MapServer/0

You'll need to set up an interactive filter on the "status" field. The layer initially loads, but when you try to select from the drop down it disappears from the map. 

status (Type: esriFieldTypeSmallInteger, Alias: Status, Domain: Coded Values: [1: New], [2: Open], [3: Closed]

**Comment by kellyhutchins** [comment]
@marissaAnn  I just ran a quick test and its working for me. Here's my test app

http://www.arcgis.com/apps/InteractiveFilter/index.html?appid=29c6225c099849d99f1c8b75e2897644

**Comment by marissaAnn** [comment]
Closing this issue as it has been resolved by the latest update to filter.js
